//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Events struct {
	Index           *int64
	DatetimeScraped *time.Time
	EventDate       *time.Time
	EventLocation   *string
	EventName       *string
	EventURL        *string
}
